In [11]:
import numpy as np
a = np.array([[0,1],[2,3],[4,5]])
b = np.array([[0,1,2,3],[4,5,6,7]])
c = np.dot(a,b)
print(c)

print('最大値は、',c.max(),'です。')

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
最大値は、 47 です。
